from .capabilities_registry import (
    CAPABILITY_CAPABILITIES_CATALOG,
    CAPABILITY_EXIT,
    CAPABILITY_HEURISTIC_RESPONSE,
    CAPABILITY_INTERNAL_COMMAND,
    CAPABILITY_INTERNAL_OPERATIONS_CATALOG,
    CAPABILITY_INTERNAL_TOOLS_ACTIVE,
    CAPABILITY_INTERNAL_TOOLS_CATALOG,
    CAPABILITY_MAINTENANCE,
    CAPABILITY_MEMORY_LOOKUP,
    CAPABILITY_MEMORY_LOOKUP_AMBIGUOUS,
    CAPABILITY_MEMORY_UPDATE,
    CAPABILITY_MODEL_RESPONSE,
    CAPABILITY_REPETITION,
    CAPABILITY_SYSTEM_STATE,
    CapabilityContext,
)
from .internal_actions_registry import (
    ACTION_CAPABILITIES_CATALOG,
    ACTION_EXIT,
    ACTION_INTERNAL_FORGET_INTERESTS,
    ACTION_INTERNAL_FORGET_NAME,
    ACTION_INTERNAL_FORGET_PREFERENCES,
    ACTION_INTERNAL_FORGET_WORK,
    ACTION_INTERNAL_OPERATIONS_CATALOG,
    ACTION_INTERNAL_TOOLS_CONTEXTUAL_HELP,
    ACTION_INTERNAL_TOOLS_CONSISTENCY,
    ACTION_INTERNAL_TOOLS_DIAGNOSTIC,
    ACTION_INTERNAL_TOOLS_DOMINANT_LIMITATION,
    ACTION_INTERNAL_TOOLS_DOMINANT_STRENGTH,
    ACTION_INTERNAL_TOOLS_FEASIBILITY,
    ACTION_INTERNAL_TOOLS_GENERAL_CHECK,
    ACTION_INTERNAL_TOOLS_GENERAL_DIAGNOSTIC,
    ACTION_INTERNAL_TOOLS_FULL_DIAGNOSTIC,
    ACTION_INTERNAL_TOOLS_INTERNAL_REVIEW,
    ACTION_INTERNAL_TOOLS_LIMITATIONS_OVERVIEW,
    ACTION_INTERNAL_TOOLS_MEMORY_AND_STATE_REVIEW,
    ACTION_INTERNAL_TOOLS_OPERATIONAL_REVIEW,
    ACTION_INTERNAL_TOOLS_PRACTICAL_REVIEW,
    ACTION_INTERNAL_TOOLS_PRIORITY_NOW,
    ACTION_INTERNAL_TOOLS_QUICK_CHECK,
    ACTION_INTERNAL_TOOLS_READINESS_GAP,
    ACTION_INTERNAL_TOOLS_STRATEGIC_GUIDANCE,
    ACTION_INTERNAL_TOOLS_SYSTEM_CHECK,
    ACTION_INTERNAL_TOOLS_SITUATIONAL_STATUS,
    ACTION_INTERNAL_TOOLS_CATALOG,
    ACTION_INTERNAL_TOOLS_COMPLETE_REVIEW,
    ACTION_INTERNAL_TOOLS_WORK_READINESS,
    ACTION_INTERNAL_QUERY_ALL,
    ACTION_INTERNAL_QUERY_INTERESTS,
    ACTION_INTERNAL_QUERY_PREFERENCES,
    ACTION_INTERNAL_QUERY_WORK,
    ACTION_MAINTENANCE_CLEAN_MEMORY,
    ACTION_MAINTENANCE_CORRECT_PREFERENCES,
    ACTION_MAINTENANCE_RELOAD_MEMORY,
    ACTION_MAINTENANCE_REVIEW_MEMORY,
    ACTION_MAINTENANCE_SHOW_LAST_LOG,
    ACTION_MAINTENANCE_SUMMARIZE_LAST_LOG,
    ACTION_MAINTENANCE_SUMMARIZE_LAST_TURN,
    ACTION_MAINTENANCE_VALIDATE_CONFIG,
    ACTION_MEMORY_LOOKUP_AMBIGUOUS_LIKES,
    ACTION_MEMORY_LOOKUP_AMBIGUOUS_NAME,
    ACTION_MEMORY_LOOKUP_AMBIGUOUS_WORK,
    ACTION_MEMORY_LOOKUP_LIKES,
    ACTION_MEMORY_LOOKUP_NAME,
    ACTION_MEMORY_LOOKUP_WORK,
    ACTION_MEMORY_UPDATE,
    ACTION_HEURISTIC_RESPONSE,
    ACTION_MODEL_RESPONSE,
    ACTION_REPETITION,
    ACTION_SYSTEM_LLAMA_PATH,
    ACTION_SYSTEM_LOADED_MEMORY,
    ACTION_SYSTEM_MODEL_AVAILABLE,
    ACTION_SYSTEM_MODEL_NAME,
    ACTION_SYSTEM_MODEL_PATH,
    ACTION_SYSTEM_STATE,
    ACTION_SYSTEM_VERSION,
)
from .internal_commands_agent import (
    INTERNAL_ACTION_FORGET,
    INTERNAL_ACTION_QUERY,
    INTERNAL_TARGET_ALL,
    INTERNAL_TARGET_INTERESTS,
    INTERNAL_TARGET_NAME,
    INTERNAL_TARGET_PREFERENCES,
    INTERNAL_TARGET_WORK,
)
from .maintenance_agent import (
    MAINTENANCE_TARGET_CLEAN_MEMORY,
    MAINTENANCE_TARGET_CORRECT_PREFERENCES,
    MAINTENANCE_TARGET_RELOAD_MEMORY,
    MAINTENANCE_TARGET_REVIEW_MEMORY,
    MAINTENANCE_TARGET_SHOW_LAST_LOG,
    MAINTENANCE_TARGET_SUMMARIZE_LAST_LOG,
    MAINTENANCE_TARGET_SUMMARIZE_LAST_TURN,
    MAINTENANCE_TARGET_VALIDATE_CONFIG,
)
from .memory_agent import MEMORY_INTENT_LIKES, MEMORY_INTENT_NAME, MEMORY_INTENT_WORK
from .system_state_agent import (
    SYSTEM_TARGET_LLAMA_PATH,
    SYSTEM_TARGET_LOADED_MEMORY,
    SYSTEM_TARGET_MODEL_AVAILABLE,
    SYSTEM_TARGET_MODEL_NAME,
    SYSTEM_TARGET_MODEL_PATH,
    SYSTEM_TARGET_STATE,
    SYSTEM_TARGET_VERSION,
)


def resolve_internal_action(
    capability: str,
    context: CapabilityContext,
) -> str | None:
    if capability == CAPABILITY_EXIT:
        return ACTION_EXIT

    if capability == CAPABILITY_CAPABILITIES_CATALOG:
        return ACTION_CAPABILITIES_CATALOG

    if capability == CAPABILITY_INTERNAL_OPERATIONS_CATALOG:
        return ACTION_INTERNAL_OPERATIONS_CATALOG

    if capability == CAPABILITY_INTERNAL_TOOLS_CATALOG:
        return ACTION_INTERNAL_TOOLS_CATALOG

    if capability == CAPABILITY_INTERNAL_TOOLS_ACTIVE and context.tools_query:
        return {
            "contextual_help": ACTION_INTERNAL_TOOLS_CONTEXTUAL_HELP,
            "diagnostic": ACTION_INTERNAL_TOOLS_DIAGNOSTIC,
            "general_check": ACTION_INTERNAL_TOOLS_GENERAL_CHECK,
            "general_diagnostic": ACTION_INTERNAL_TOOLS_GENERAL_DIAGNOSTIC,
            "full_diagnostic": ACTION_INTERNAL_TOOLS_FULL_DIAGNOSTIC,
            "priority_now": ACTION_INTERNAL_TOOLS_PRIORITY_NOW,
            "dominant_limitation": ACTION_INTERNAL_TOOLS_DOMINANT_LIMITATION,
            "dominant_strength": ACTION_INTERNAL_TOOLS_DOMINANT_STRENGTH,
            "limitations_overview": ACTION_INTERNAL_TOOLS_LIMITATIONS_OVERVIEW,
            "situational_status": ACTION_INTERNAL_TOOLS_SITUATIONAL_STATUS,
            "strategic_guidance": ACTION_INTERNAL_TOOLS_STRATEGIC_GUIDANCE,
            "feasibility_evaluation": ACTION_INTERNAL_TOOLS_FEASIBILITY,
            "consistency_evaluation": ACTION_INTERNAL_TOOLS_CONSISTENCY,
            "quick_check": ACTION_INTERNAL_TOOLS_QUICK_CHECK,
            "readiness_gap": ACTION_INTERNAL_TOOLS_READINESS_GAP,
            "system_check": ACTION_INTERNAL_TOOLS_SYSTEM_CHECK,
            "work_readiness": ACTION_INTERNAL_TOOLS_WORK_READINESS,
            "memory_state_review": ACTION_INTERNAL_TOOLS_MEMORY_AND_STATE_REVIEW,
            "practical_review": ACTION_INTERNAL_TOOLS_PRACTICAL_REVIEW,
            "operational_review": ACTION_INTERNAL_TOOLS_OPERATIONAL_REVIEW,
            "internal_review": ACTION_INTERNAL_TOOLS_INTERNAL_REVIEW,
            "complete_review": ACTION_INTERNAL_TOOLS_COMPLETE_REVIEW,
        }.get(context.tools_query.mode)

    if capability == CAPABILITY_MEMORY_LOOKUP:
        return {
            MEMORY_INTENT_NAME: ACTION_MEMORY_LOOKUP_NAME,
            MEMORY_INTENT_WORK: ACTION_MEMORY_LOOKUP_WORK,
            MEMORY_INTENT_LIKES: ACTION_MEMORY_LOOKUP_LIKES,
        }.get(context.memory_intent)

    if capability == CAPABILITY_MEMORY_LOOKUP_AMBIGUOUS:
        return {
            MEMORY_INTENT_NAME: ACTION_MEMORY_LOOKUP_AMBIGUOUS_NAME,
            MEMORY_INTENT_WORK: ACTION_MEMORY_LOOKUP_AMBIGUOUS_WORK,
            MEMORY_INTENT_LIKES: ACTION_MEMORY_LOOKUP_AMBIGUOUS_LIKES,
        }.get(context.memory_intent)

    if capability == CAPABILITY_MEMORY_UPDATE:
        return ACTION_MEMORY_UPDATE

    if capability == CAPABILITY_REPETITION:
        return ACTION_REPETITION

    if capability == CAPABILITY_INTERNAL_COMMAND and context.internal_command:
        return {
            (INTERNAL_ACTION_QUERY, INTERNAL_TARGET_ALL): ACTION_INTERNAL_QUERY_ALL,
            (INTERNAL_ACTION_QUERY, INTERNAL_TARGET_WORK): ACTION_INTERNAL_QUERY_WORK,
            (INTERNAL_ACTION_QUERY, INTERNAL_TARGET_INTERESTS): ACTION_INTERNAL_QUERY_INTERESTS,
            (INTERNAL_ACTION_QUERY, INTERNAL_TARGET_PREFERENCES): ACTION_INTERNAL_QUERY_PREFERENCES,
            (INTERNAL_ACTION_FORGET, INTERNAL_TARGET_NAME): ACTION_INTERNAL_FORGET_NAME,
            (INTERNAL_ACTION_FORGET, INTERNAL_TARGET_WORK): ACTION_INTERNAL_FORGET_WORK,
            (INTERNAL_ACTION_FORGET, INTERNAL_TARGET_INTERESTS): ACTION_INTERNAL_FORGET_INTERESTS,
            (INTERNAL_ACTION_FORGET, INTERNAL_TARGET_PREFERENCES): ACTION_INTERNAL_FORGET_PREFERENCES,
        }.get((context.internal_command.action, context.internal_command.target))

    if capability == CAPABILITY_SYSTEM_STATE and context.system_state_command:
        return {
            SYSTEM_TARGET_STATE: ACTION_SYSTEM_STATE,
            SYSTEM_TARGET_MODEL_NAME: ACTION_SYSTEM_MODEL_NAME,
            SYSTEM_TARGET_MODEL_PATH: ACTION_SYSTEM_MODEL_PATH,
            SYSTEM_TARGET_LLAMA_PATH: ACTION_SYSTEM_LLAMA_PATH,
            SYSTEM_TARGET_MODEL_AVAILABLE: ACTION_SYSTEM_MODEL_AVAILABLE,
            SYSTEM_TARGET_VERSION: ACTION_SYSTEM_VERSION,
            SYSTEM_TARGET_LOADED_MEMORY: ACTION_SYSTEM_LOADED_MEMORY,
        }.get(context.system_state_command.target, ACTION_SYSTEM_STATE)

    if capability == CAPABILITY_MAINTENANCE and context.maintenance_command:
        return {
            MAINTENANCE_TARGET_VALIDATE_CONFIG: ACTION_MAINTENANCE_VALIDATE_CONFIG,
            MAINTENANCE_TARGET_REVIEW_MEMORY: ACTION_MAINTENANCE_REVIEW_MEMORY,
            MAINTENANCE_TARGET_RELOAD_MEMORY: ACTION_MAINTENANCE_RELOAD_MEMORY,
            MAINTENANCE_TARGET_CLEAN_MEMORY: ACTION_MAINTENANCE_CLEAN_MEMORY,
            MAINTENANCE_TARGET_SHOW_LAST_LOG: ACTION_MAINTENANCE_SHOW_LAST_LOG,
            MAINTENANCE_TARGET_SUMMARIZE_LAST_LOG: ACTION_MAINTENANCE_SUMMARIZE_LAST_LOG,
            MAINTENANCE_TARGET_SUMMARIZE_LAST_TURN: ACTION_MAINTENANCE_SUMMARIZE_LAST_TURN,
            MAINTENANCE_TARGET_CORRECT_PREFERENCES: ACTION_MAINTENANCE_CORRECT_PREFERENCES,
        }.get(context.maintenance_command.target)

    if capability == CAPABILITY_MODEL_RESPONSE:
        return ACTION_MODEL_RESPONSE

    if capability == CAPABILITY_HEURISTIC_RESPONSE:
        return ACTION_HEURISTIC_RESPONSE

    return None
